Repository GEOS-ESM/GEOSAQcGAN, pull requests merged in 2025-05, with the labels that each got.

#3 Pcastell/geos dataset
  CHANGELOG.md
  src/geosaqcgan/CMakeLists.txt
  src/geosaqcgan/geos_dataset.py
  src/geosaqcgan/geosaqcgantrainer.py
  src/geosaqcgan/inference/create_predictions.py
  src/geosaqcgan/scripts/preprocess_geos_cf.py
  src/geosaqcgan/scripts/read_geos_cf_datafiles.py
  src/geosaqcgan/shared/aqcgan_utils.py
  src/geosaqcgan/shared/gen_utils.py
  src/tests/forecast/geos_cf_perturb_met_and_emis_gcc_feb_sep_surface_only_time_8ts_nolstm_nolatlon_none_train_7_28_12_17_29_3_1_25_20_19_24_23_22_15_8_26_21_5_9.yaml
  src/tests/forecast/geos_cf_preproc_collections.yaml
  src/tests/forecast/norm_stats.pkl
  src/tests/forecast/run_fc.sh
  src/tests/forecast/train_metrics.pkl
  src/tests/forecast/val_metrics.pkl
Labels: 0 diff structural

#4 Jk combine preproc and predictions
  CHANGELOG.md
  src/geosaqcgan/configs/geos_cf_preproc_collections.yaml
  src/geosaqcgan/geos_dataset.py
  src/geosaqcgan/inference/create_predictions.py
  src/geosaqcgan/scripts/preprocess_geos_cf.py
  src/geosaqcgan/scripts/read_geos_cf_datafiles.py
  src/geosaqcgan/shared/gen_utils.py
  src/tests/CMakeLists.txt
  src/tests/forecast/CMakeLists.txt
  src/tests/forecast/geos_cf_preproc_collections.yaml
  src/tests/forecast/norm_stats.pkl
  src/tests/forecast/run_fc.sh
  src/tests/forecast/train_metrics.pkl
  src/tests/forecast/val_metrics.pkl
Labels: 0 diff structural

#5 Set up process for a forecast run
  CHANGELOG.md
  src/tests/forecast/CMakeLists.txt
  src/tests/forecast/forecast_run.j
  src/tests/forecast/forecast_setup.py
  src/tests/forecast/run_fc.sh
Labels: 0 diff structural

#6 Update CHANGELOG.md for release v1.0.0
  CHANGELOG.md
Labels: 0 diff trivial

#7 v1.0.0
  .gitignore
  CHANGELOG.md
  README.md
  cmake_it
  components.yaml
  src/CMakeLists.txt
  src/Shared/CMakeLists.txt
  src/Shared/JHU_Shared/.gitignore
  src/Shared/JHU_Shared/CMakeLists.txt
  src/Shared/JHU_Shared/__init__.py
  src/geosaqcgan/CMakeLists.txt
  src/geosaqcgan/__init__.py
  src/geosaqcgan/configs/geos_cf_preproc_collections.yaml
  src/geosaqcgan/geos_dataset.py
  src/geosaqcgan/geosaqcgantrainer.py
  src/geosaqcgan/inference/create_predictions.py
  src/geosaqcgan/scripts/preprocess_geos_cf.py
  src/geosaqcgan/scripts/read_geos_cf_datafiles.py
  src/geosaqcgan/shared/aqcgan_utils.py
  src/geosaqcgan/shared/gen_utils.py
  src/tests/CMakeLists.txt
  src/tests/forecast/CMakeLists.txt
  src/tests/forecast/forecast_run.j
  src/tests/forecast/forecast_setup.py
  src/tests/forecast/geos_cf_perturb_met_and_emis_gcc_feb_sep_surface_only_time_8ts_nolstm_nolatlon_none_train_7_28_12_17_29_3_1_25_20_19_24_23_22_15_8_26_21_5_9.yaml
  src/tests/forecast/run_fc.sh
  src/tests/validate/CMakeLists.txt
  src/tests/validate/geos_cf_perturb_met_and_emis_gcc_feb_sep_surface_only_time_8ts_nolstm_nolatlon_none_train_7_28_12_17_29_3_1_25_20_19_24_23_22_15_8_26_21_5_9.yaml
  src/tests/validate/meta.pkl
  src/tests/validate/norm_stats.pkl
  src/tests/validate/run_val.sh
  src/tests/validate/train_metrics.pkl
  src/tests/validate/val_metrics.pkl
Labels: enhancement, 0 diff structural
